title: Mark Flynn
#logo: /assets/img/logo.png
#description: website duplicating my resume & showcasing some of my interests & hobbies
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal

